In [ ]:
import torch as t
from torch.autograd import Variable

a = Variable(t.randn(3,4))
b = Variable(t.randn(3,4))

In [13]:
print(a,b,sep='\n')
a.add(b)
print(a,b,sep='\r')

tensor([[-0.2298,  1.8780,  0.9769, -1.3086],
        [-0.0697, -2.1719, -4.4787, -0.1577],
        [-0.0551,  2.1034, -1.0063, -0.8065]])
tensor([[-0.7257,  0.8540,  0.8830, -0.9073],
        [ 0.5716, -1.0424, -2.2145,  0.8847],
        [-1.1928,  1.0227,  0.2849,  0.1086]])
tensor([[-0.2298,  1.8780,  0.9769, -1.3086],
        [-0.0697, -2.1719, -4.4787, -0.1577],
tensor([[-0.7257,  0.8540,  0.8830, -0.9073],
        [ 0.5716, -1.0424, -2.2145,  0.8847],
        [-1.1928,  1.0227,  0.2849,  0.1086]])
